### ISSUE TITLE
Extended for Rotation

### ISSUE THREAD

**Issue by KriekyNies** [jmalarcon/jquery.pan#1]
Found this tool to be super useful, quick, elegant, and extremely simple to use.  However, many of the images we deal with in web apps on a day-to-day basis originate as scans which can arrive in unpredictable orientations, so the lack of rotation capability was a pain point for us.  So I made a few quick additions to your code to allow for rotation and will attach them here.  Also updated the control icons to make them a bit more visible since we found the original controls were too hard for many users to spot.

Extracting the current transition state directly from CSS styles is difficult, so the rotation functions which I've added lean on storing the current rotation state in a 'data-' attribute of the 'PanImg' element.  This has the added benefit of your preferred rotation being sustained throughout a page session even if you close the image previewer and return to it later.

I haven't done much in the way of platform testing the additions, but verified they work as expected on at least Chrome (79), IE(11), Edge, and Droid Chrome.  Rather than fork your project - just passing along my adjustments and will leave it up to you if you think they are worth inclusion in an update, or inspire something similar of your own making.

![zoomOut](https://user-images.githubusercontent.com/47507322/73986177-3071a700-48fa-11ea-8c76-8f25c48fa1d5.png)
![close](https://user-images.githubusercontent.com/47507322/73986178-310a3d80-48fa-11ea-89b9-957170cb83bd.png)
![rotateAntiClockwz](https://user-images.githubusercontent.com/47507322/73986180-310a3d80-48fa-11ea-8efe-9ffd5ea042c3.png)
![rotateClockwz](https://user-images.githubusercontent.com/47507322/73986181-310a3d80-48fa-11ea-8a42-62bff2f94267.png)
![zoomIn](https://user-images.githubusercontent.com/47507322/73986182-31a2d400-48fa-11ea-8ee3-04ae10c27f22.png)

**Additions to jquery.pan.css:**

```
.panWrapper a.controls.rc {
    background-image: url('img/rotateClockwz.png');
    margin-left: 60px;
}

.panWrapper a.controls.ra {
    background-image: url('img/rotateAntiClockwz.png');
    margin-left: -60px;
}
```

**Additions to jquery.pan.js:**
_icon instantiations_
```
		var rc = document.createElement('a');
		$(rc).addClass("controls rc");
		$(panWrapper).append(rc);

		var ra = document.createElement('a');
		$(ra).addClass("controls ra");
		$(panWrapper).append(ra);
```
_and two new functions_

```
		$(rc).click(function (e) {
			var panImg = $(".panWrapper img.i");
			var angle = (panImg.data('rotAngle')) || 0;
			angle += 90;
			if(angle > 360){angle = angle-360};
			panImg.css({'transform' : 'rotate(' + angle + 'deg)'});
			panImg.data('rotAngle', angle);
			panInit(e);
		});

		$(ra).click(function (e) {
			var panImg = $(".panWrapper img.i");
			var angle = (panImg.data('rotAngle')) || 0;
			angle -= 90;
			if(angle < 360){angle = angle+360};
			panImg.css({'transform' : 'rotate(' + angle + 'deg)'});
			panImg.data('rotAngle', angle);
			panInit(e);
		});
```

**Comment by jmalarcon** [comment]
Hi @KriekyNies 

Thanks for the contribution.

I'll definitely will take a look to it as soon as I can and add them to the library.

I'll let you know.

Thanks!

**Comment by jmalarcon** [comment]
Hi again @KriekyNies 

I've updated the package adding support for rotation. However I needed to do much more than what you did because the way you're doing it doesn't support the panning of the image correctly.

Since the original code positioned the zoomed image using absolute position, when you rotate the image the coordinate system changes too and the absolute position simply doesn't work. I've rewritten the positioning logic to position the image using transforms too. That (and the rotation itself) removes support for IE 8 and 9, and the plugin now only works with IE10+ (fair enough these days).

Apart from that I've limited internally the rotation between 0 -360 degrees. Although in practice there's no difference and you can rotate clockwise or aws as much as you want, internally it's limited that way. 

Rotation controls can be hidden and disabled (makes sense in many situations) just by passing a `false` argument to the `pan()` method (read the `readme.md` page for details).

I've created new action icons, more neutral and at the same time being able to be spotted easily under most circumstances. honestly I didn't liked the yellow glowing in your new version. But obviously you can change them locally in your app and they'll work OK.

It doesn't keep the state of rotation as you suggested, though. I don't see that this make sense in most of the applications (maybe in yours, but not in 99% I can think of). Every time an image is loaded for zoom, pan and rotate, it's shown in ins original position and size.

Finally I've added support to show loading progress (it had a GIF image but was never implemented) and squashed a minor bug.

You can check the new version in action  [in the demo page](https://jmalarcon.github.io/jquery.pan/).

Hope you like it although it's not exactly what you wanted (but mostly).

Thanks for the suggestion, although finally I haven't used most of it. It has made the plugin better 😊 

It's already in "releases" and in the npm repository.

Cheers!
