### ISSUE TITLE
Different axis move depending on image orientation (landscape/portrait)

### ISSUE THREAD

**Issue by bichonnages** [jmalarcon/jquery.pan#2]
Hi
Quick question:
Would it possible to change/block the axis move depending on image orientation?
To be more precise, I'd like to:
— allow the horizontal axis move/block the vertical axis move for landscape images (the image height would be the viewport height)
— allow the vertical axis move/block the horizontal axis move on portrait image (the image width would be the viewport width).

Great fork btw 👍

**Comment by jmalarcon** [comment]
Hi:

If I understand you correctly, what you want is to limit the width or height of the image depending on its orientation so that the maximum zoom would be in that dimension, and the pan action would only happen on the other axis?

I think this is a totally different goal for the plugin, a very specific one. It will probably imply a lot of work (probably a rewrite of the main logic) and it'll be difficult to adapt to windows resizing, etc... 

I think it's a work for a different plugin, sorry.

Hope you enjoy the current one anyway.

Cheers!
